(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file))

(load "~/.emacs.d/modules/gui.el")
(load "~/.emacs.d/modules/backup.el")
(load "~/.emacs.d/modules/packages.el")
(load "~/.emacs.d/modules/navigation.el")
(load "~/.emacs.d/modules/editing.el")
(load "~/.emacs.d/modules/ffap.el")
(load "~/.emacs.d/modules/prog.el")
(load "~/.emacs.d/modules/c-common.el")
(load "~/.emacs.d/modules/go.el")
(load "~/.emacs.d/modules/python.el")
(load "~/.emacs.d/modules/emacs-lisp.el")
(load "~/.emacs.d/modules/json.el")
(load "~/.emacs.d/modules/java.el")
(load "~/.emacs.d/modules/latex.el")
(load "~/.emacs.d/modules/text.el")
(load "~/.emacs.d/modules/graphviz-dot.el")
(load "~/.emacs.d/modules/sh.el")
(load "~/.emacs.d/modules/markdown.el")
(load "~/.emacs.d/modules/rst.el")
(load "~/.emacs.d/modules/feature.el")
(load "~/.emacs.d/modules/js2.el")

(shell)
(delete-other-windows)
